interface DatosSesion {
    nit: string
    razonSocial: string
    nombreUsuario: string
    email: string
    idBaseDatos: number
    helpDeskNuevo: boolean
    IdObra: number
    NomObra: string
    NomEmpresa: string
    NombreEmpresa: string
    NitEmpresa: string
    SucursalProyecto: string
    CambiarClave: boolean
    idProyectoSGP: number
    nombreProyectoSGP: string
    USUhelpDeskSinco: string
    LgoEmpresa: string
    urlFuentes: string
    idPerfil: string
    nombreApp: string
    ctaCorreoInactiva: boolean
    id: string
    USER_NAME: string
    token: string
    idOrigen: string
    NomUsuario: string
    idUsuario: string
    idEmpresa: string
    IdSucursal: string
    user_ip: string
    uid: string
    UsuDominio: string
    idEmpresaCliente: number
    NombreSucursal: string
    PrimerIngreso: boolean
    EsReplica: boolean
    MostrarPanelControl: boolean
    user_name: string
    URL_Entorno: string
  }