// Generated by https://quicktype.io

import { UltimaModificacion, Ciudad, TipoDocumento } from '../definitions';

export interface DataEmpresa {
  Id: number;
  Nit: string;
  RazonSocial: string;
  ConstitucionEmpresa: string;
  Direccion: string;
  UrlLogo: string;
  Poliza: Poliza;
  RepresentanteLegal: RepresentanteLegal;
  Ciudad: Ciudad;
  UltimaModificacion: UltimaModificacion;
}

export interface Poliza {
  Numero: string;
  Valor: number | string;
}
export interface RepresentanteCommon {
  NombreCompleto: string;
  NumeroIdentificacion: string;
  LugarExpedicion: string;
}
export interface RepresentanteLegal extends RepresentanteCommon {
  TipoDocumento: TipoDocumento;
  Firma: string;
}

export interface RepresentanteUpdate extends RepresentanteCommon {
  TipoDocumento: string;
}
export interface EmpresaUpdate {
  Direccion: string;
  Ciudad: Ciudad;
  Descripcion: string;
  Poliza: Poliza;
}
export interface setEmpresaUpdate {
  ConstitucionEmpresa: string;
  Numero: string;
  Valor: number | string;
  Direccion: string;
  Ciudad: number | string;
}

export interface Firma {
  Nombre: string;
  Imagen: string;
}
